# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:Srfu53l/H3clsw8/cpbIL71N1AbWNFzAm/eWcjfzRvIN5DF65qS5xJr5miWBULLy+czfTnsh22rL77argy6nx0BHIVkO9GQGy+vV0L2CF4CG/CRV6t7CJZjCWRI415FUKIEte4F0mrJGZF404kaoqX3tVdNCO9GLqt2kSRTNz1gAc01/KZLBWuNaDFhh3tm1wHtnZraU+mlHozvIZHzYRQfS1XFGUtt36GnCDkiUgr4V2f7Oyg==,iv:YdqzwW0yRAQJN/mSm70EQEueRuxTgCEEgjzhv5S4tWE=,tag:xJYVvaJdlCte10Slpgl2iA==,type:str]
sops:
  age:
    - recipient: age1jnljcfz93u3e8fs2rtc5g8e5rpdjndsa9rz9pjpany8f0w65mfdspcm2vz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiR2Q2cXZ2UmQrL05QSHpP
        UVNkNk9iYnA5YzJkb0NFbCs5SU9SLytDdHkwCnpvQ3lMYWlwQkwvQkV6V2dqNS9u
        ZHZ5aWUvUkwxVUNnYnV6VUpXUkdKWUEKLS0tIDJaM0FTalYxdnZtTGp3UWJVV0ZR
        Q2RVQWl2dUpsQ01NSVgxT1pZaW16UHMKMnC153tG+Jp/4x6lRrrLnQsX07uzvtic
        Kks77pT6RLNyrwgaYk+SLgecWJhk76TONTsCcsY7BzA6Fjqr6lt1NQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-22T04:29:25Z"
  mac: ENC[AES256_GCM,data:wNtN4T4bfkZz64BvxjKKqHgAtpagOvbWjqqbPR3VoZI+7i6qa/J4a6XQndbUpBHL9Ya81S8UJ3Wup0mgFTuuIkevnAc8yCM3yI9AIfb0OHkmNXxVOLDhZ6rNrv3yVoWIskfidSLe2ZUt8G73bIUBRtTrhadPiSEKBaO8Yd7jaVg=,iv:Zo1Gje1mHI5BttWegSnZGn14Nzo0S52H8Eu7+zk1P0Y=,tag:c4Zr53hKcIOOVtcNmxNO5A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
