---
version: 3

vars:
  TERRAFORM_DIR: "{{.ROOT_DIR}}/infrastructure/terraform"

includes:
  tf: ".taskfiles/Terraform/Taskfile.yaml"

tasks:
  age:
    dir: "{{.ROOT_DIR}}"
    cmd: age-keygen -o age.key

  default:
    cmd: "task -l"
