# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:wPKQelIwWJkCmY6DyVSwQZ9sO+Z9nvZ1vNlfFLEr/y+fwYZD2WUS/A==,iv:zM+ILUKOEuO1525HM/bkAWMXQp9vZ9o19gDO2jpFvtQ=,tag:6mn6yyn09+0nGO4HKqzRbg==,type:str]
sops:
  age:
    - recipient: age1jnljcfz93u3e8fs2rtc5g8e5rpdjndsa9rz9pjpany8f0w65mfdspcm2vz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKMmUrQUFNdUNabElReE9P
        Sk95TUNVZHdhQjJTNGpBdmJQRStYNXcwRGhNCnBWRGFPYytERjl0czE3VnRNNkpX
        R29EMEZrWVpHbDFJUnlHMXphaWxzZDAKLS0tIGFrR05PYWJEcXI5ZVdPZHFoUEhk
        R0VnR1lPSGVaWXFoNjZjb1F2WHZXM3MKZ49dkcZr4ekBlN/8u0Ef1SsH9j2yTU/l
        lSFDoPuoHNcyOGdrw0SJA5B/BCkJ0xSAq3UKKbTGCxcSBM/HbptNEg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-22T04:29:25Z"
  mac: ENC[AES256_GCM,data:BZMiUYVVKLyvwF/EheHmGVQBhZT9Ihpe0fZjQwQiUPpZDEdZ24bUEqqy6AL7xddBu42Fz6BCvL37MUvH6Qdcb4iSf4B+ZkjJ7BMO6uUU5EV7Wh0Uu4t+CF3npN+aoNQrDOGSQt67XNveo3U1CulyUSdx7SiJ7jFoCpOH4Cb4MiE=,iv:EKC/0paRsDP/9GePLen5MfshTPZ30hdrDwf+3feBtcw=,tag:nw2kAGew1FNwdPB6F1WKMw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
