# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:l3XujmxZT2It6C6tq6sS8KfEd8gcURO/vQlB8jn6ivk=,iv:S3d7ddDipg9gdHd11xEhaUAhkCzcIkx/FlvUnlLIg74=,tag:COENSx5hYkbwm+2HoWjlXw==,type:str]
sops:
  age:
    - recipient: age1fxaf2letwe992ynqxuaguhsdua6negmdgsgcklsnk4lgyp2dz34sgn5dw9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ZkNpTXVyQ0tkOTdnQkZy
        ZHJrZGNZT2tPZVJuQW9LcXJqNHhyQlZ3b0M4CjQrSW9LVnJGY09RQ2VwcFkxWnJW
        VXJlRkNuZlc1bDVPdEVscTArUzZMRzAKLS0tIDlwRVdneVc3MlJPVXVsZnJQN2pm
        YnBqQnNsL1NZaktzR1A2bjB6SERNVnMKED5OPnyzZZbevNY/lN//nlW1PNv6t95t
        WO85wpIx8HQpmCW46mzCY+KNGOWGXDKR0wi010/5/YMfVX1R0f8W7A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-28T23:26:13Z"
  mac: ENC[AES256_GCM,data:y6XOVUQ8gJM/9+BReS/ot6NsDapjE042DPCZotLtde9EDnZqXxMYHm86ai6rBgEREYLXswgnwaJyHnu+8K0Mt/3H1HLQwp9TS2oyaVQenSXlGduhxYHgsQd+l3vmKB1t7cM11VaMD9VeH05HEHqZyqHqr53t6eTZIFWZLYXRrbc=,iv:RTGmWncYiWMcK4er5sBGgjaUwg6OFQMCNTC+D7tjQPs=,tag:cuSbfVMdSM8CVyXfM4sdvQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
