# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:VvGlGe74D7bhqPaLKIrCMCBYylRcxV866WibgClCop2XIRypQP+Zsl9Ke7whYzfM28HAGcojciRCUoQozt5mbcZNoCOs2UkIBrMGHXkttwvhXZ1MXBYCP0POkNA8XOBMPnSYnlR3TKwwKFxSllHabwLPEus7tTa5XK2sHjXipv9dy9PThYN73/XQPH41o5r0X8Fu4J/n55qIMcbpDvceZ+jkCM1HwSjUM1ZFeXJkub1Fa//dzQ==,iv:hkUvkKnld5X7mnE9PpI4Pypyk8eX2JViDFtbpmyAmK0=,tag:AhYd574qbCk9Dm5Tu+RJ0A==,type:str]
sops:
  age:
    - recipient: age1fxaf2letwe992ynqxuaguhsdua6negmdgsgcklsnk4lgyp2dz34sgn5dw9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWS9rdTN3cUtYMEYrUTZn
        a2lZM091MHNmbnFpRzBLSk90eit1OW90MFhFClJVd1U0WUJrK0M5NTR5b3NZRHo2
        LzlDZUlvMHVRbGpUZWM3MDZrWFZTVVkKLS0tIEhrWkIxaU92M1BwVjBOaGFZK0dz
        azkwUnRpbmc1MEpQekt1VHpGeXpTQk0KIC0rokKrC4Kb3MPKg/iUtfuZ/hrfhbTF
        3SMjq9oEmHfqXncRaaRpYgCmjoYT0ArcCiA9FUwg3sYzC32OzRCc5A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-28T23:26:13Z"
  mac: ENC[AES256_GCM,data:GPvTDgm22k5VUhYqUBmzZUtfV1a5uSYtze3xs0NIObsqW9LeaCpw3pA1YW68Tu34K1PBUpxszYblw5fceNybEHCA9aTFxtjfleAuINtlbQT7Nv69Z8TNt9lzTCVj8s1ddR3J4FxXm5/n7W1AftLceanwizQXf7DUfRulMVGNPSI=,iv:eJKx94C/tfrlZeJNwzzNcGcvObaH7D6I3wzCNEC7iEk=,tag:wQng7UMfBD7h+ZAVWcnDxg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
