apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:muZy8L+hG+1mXpc=,iv:AOElT+BkZaHt2Bcy5Qq0Ohi/BkpgADp6mbech7F5WTM=,tag:Q1o0XNgJK+bXMl6tt21tIA==,type:str]
sops:
  age:
    - recipient: age1jnljcfz93u3e8fs2rtc5g8e5rpdjndsa9rz9pjpany8f0w65mfdspcm2vz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Z1lHbTJaaG00YzJoL0ox
        MHFoc3VEcm92ZUxDVjBtQ3IvTS9reTFkVUNRCkg3ZUpVblFVS0lCZjRKRHJnRU1z
        emQ3ZjRBc2R0dFQxcy9RMnFYbk42cmMKLS0tIDZVclZiaEdTMWhyempoR3J3QlZq
        akUveFREY1N2cHRpdWhMSmJTZmJBYjQKjrYlWjv7jvkMe0YLksv4FUgrnhcwQC5u
        dnv2gf/1lx5yyAOtn90+hc80V1oKXrMSVbFwwBewXNlmqMLdzZUsgQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-22T04:29:24Z"
  mac: ENC[AES256_GCM,data:cK++qMGgWFMpVbV2SGUwgaEGpQI1jW/cyJzyEMUZVkmmYd1Yizy7wAgFgs/gyUhgl38wDzMvZ7KKCOYJ4vFnyYv7574bdwiPIqz1ouQnMCTp4Fuv04YMQQsKuqnMP06sZb3BvUh5Z6sdNrpfHed9fFvHjQP23/trr8mbPhy+kiw=,iv:/e/9f8BfoLz+RDt2BoH4hhK3Zk2uGsMT+PC01b5caF8=,tag:fSvPQcV7vfBVVfKc6u4KUA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
