# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:KYXryVHNG2chFp4RuTPUTIFZI/MU2XEgR4ac9ze/z08WMzga3+dS0Q==,iv:nklpSvw5Tmr5/DNRBXVIKKDu7sOIeT01RD4dwkcwEtg=,tag:DagWPXdHusvTuuUfiUJU6A==,type:str]
sops:
  age:
    - recipient: age1fxaf2letwe992ynqxuaguhsdua6negmdgsgcklsnk4lgyp2dz34sgn5dw9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZC8ya1lyL1I2YkUyazR4
        V2JmYURFWENEOHhWcktyRTFtd1g4WUZsTjNnCjh2ZS95V3dtMnp6VlpQU1ZFRWpI
        V0V2WkdTN000TjNaZjdueTRVMTNFZnMKLS0tIFZXbGRKdTBUMDBpdWZUVkh4eWJB
        NlMwNEhuMmhPR0MrbXRabjYrQjNEUHcKmTNvBx8JOlofzLrK3Te2zCsm+u6DuTJA
        klH/4TmXLAoK94n2B0O8Br0ioipJNeLUSGFbDKCR88M/yeYn+Hkj3Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-28T23:26:13Z"
  mac: ENC[AES256_GCM,data:PXV7f92IL5jTtxRTiiRx5WPXIniAgbdMALOQqTI4OjsokqDNzCf6crVjzYuvW8CWbd8WjpY/UOMRtInHtNMfnDCDez/Kfh1XJ/mcbIYyn/qU/46N7akRVOGyVMEGh32nNS6pjWIoxkmjeeKFKadzR5FFSTtwxpY/ZNGdGzDSm+k=,iv:i6eKj3MDp3rBR3y5VdFVp6RgNc9m9CHmi86FHB8mXvU=,tag:J+dPsSV6Nh8OaWOYjY+V7w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
