# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:y7Gc/26svl7bcI/OcUtoMcpcrfaGEG3wS4uL992YmXOLXx9aMJQWuw==,iv:I63oNLoJHb8acjtWbwxkNhxMFf1I4YY8V7m+dkV+kJs=,tag:LGPc5H8kW77c/2yfOI5SvQ==,type:str]
sops:
  age:
    - recipient: age1jnljcfz93u3e8fs2rtc5g8e5rpdjndsa9rz9pjpany8f0w65mfdspcm2vz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBldmp5akpSZUlxUElpT2dT
        NFd4dlc4SVFvMHZkQS9jYndIOS90a0NPWnhBCkVPNk5veUFaRWtqOXVtYnFVK1pP
        TDJmdGRZS0pRdjVxZ0JUeUY3NG1MV0kKLS0tIE1MZXUwT1kwWFZxTGkxMmFGYkhE
        RU9saEVUY0I1UDFZMGhoU0JrQmk1eEEKQUEWWwK4xp0Yf6THDP7zGg06mP7gzkw0
        RmGRYLDdtjXVV+fJMmItXroHqv/owCxsesZZ/EULc31vbAzw7W1tvg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-22T04:29:25Z"
  mac: ENC[AES256_GCM,data:1qeFd5rJ2xpG9Ow/ckYn4w6yB869GfF8rPjxrEa6O5s9p381cTl6ppacorxbL8NV3DbsEpy4Zu6B2rfTc2BKb5qiaJfZWmd0FpOsP77BKOiHSuoMXoS8KUjQInWv9FFK/QVpgOjVnaj22PbS4zlXn/G/EvL7A581AEYo8u1r3Qo=,iv:06KSpRsqkXsLZIFpzgotf1AJ7KUCzaCCaoEGtgPK/nc=,tag:hTU42FBauUEYy8sGbUS0eQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
