# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.1.120:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.1.120"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "talos-controller"
    ipAddress: "192.168.1.68"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: true
    talosImageURL: factory.talos.dev/installer-secureboot/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:45:e9:fe"
        dhcp: false
        addresses:
          - "192.168.1.68/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.1.1"
        mtu: 1500
        vip:
          ip: "192.168.1.120"
  - hostname: "worker-1"
    ipAddress: "192.168.1.198"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: true
    talosImageURL: factory.talos.dev/installer-secureboot/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:1a:63:97"
        dhcp: false
        addresses:
          - "192.168.1.198/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.1.1"
        mtu: 1500
  - hostname: "worker-2"
    ipAddress: "192.168.1.222"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: true
    talosImageURL: factory.talos.dev/installer-secureboot/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:ec:9b:e5"
        dhcp: false
        addresses:
          - "192.168.1.222/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.1.1"
        mtu: 1500
  - hostname: "worker-3"
    ipAddress: "192.168.1.47"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: true
    talosImageURL: factory.talos.dev/installer-secureboot/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:f7:27:65"
        dhcp: false
        addresses:
          - "192.168.1.47/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.1.1"
        mtu: 1500

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"

