apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:M9+yuGqp9cSmp+8=,iv:3E7KzCMMTJHDIhN/BzUMx9k7UkiaF4RO7WlyVBshRtg=,tag:sOwrArvppxCJH814gdBPFA==,type:str]
sops:
  age:
    - recipient: age1fxaf2letwe992ynqxuaguhsdua6negmdgsgcklsnk4lgyp2dz34sgn5dw9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZk9DdDRRY1hzS1p6VTFK
        cUt2ZEdCOTRFVUtmTWRONTNSV0RYMG5nZnc0CjdCQWQzcWlDUXpxVkJWM3RBSFht
        UnZDckJyMlJzdi9SOFZPdEZjSmQ5Um8KLS0tIFFmUk5FNVJMN2svWkpNS2cxWGlw
        WHJBckNib0kzUlk0MmZ3S0NvNUJmNncKso08MaGRlLxVZq9FOT+hhD9/o3MunKE4
        v/OPgpUWp9XOWEoBwVZfSxpXBJbd0xN0z+s+pC8a+TC6N861uGpPqA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-28T23:26:13Z"
  mac: ENC[AES256_GCM,data:Mxzad7MV11p0gISIpgcpSa0kz6efmfXnfc9CSyN5IV08ApR3ap7LrQq7aHqZYlYsS36nHxnchJ8hXZutj71p/wF6lRWw6C+TOYhIybS0kfzk20HjV5n6hlr4/akGTAyLkdAyVOxQ1Rap8KjsRpddov6PqXDawEXTskpDRVpNo/M=,iv:v43ow69AeENpRlfel6WE3QKVTxYqEGiUk2kELZCDf/U=,tag:ZJCIdyPPK3ojx3YvUHdE5A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
